#
#  Configuration file for BitWave Bio
#     https://github.com/BitWaveOrg
#           https://five.bio
#

user_firstname: 'v3sker' # Username shown on profile (Required)
userbio: 'Making my way in the Full-Stack Web Development.' # Profile description (Required)

linkedin_login: '' # LinkedIn login (Optional)
telegram_login: 'reKs3v' # Telegram login (Optional)
discords_login: 'v3sker' # DiscordS login (Optional)
steam_login: 'v3sker' # SteamCommunity ID (Optional)
instagram_login: 'v3skerxd' # Instagram login (Optional)
twitter_login: 'v3skerxd' # Twitter login (Optional)
website_url: 'https://v3sker.site' # Website url (Optional)
cv_url: '' # CV URL (Optional)

profile_theme: 'dark' # Profile style
profile_color: 'rgb(0,0,0)' # Profile border color
